[[main]]
name = "About Me"
title = "About Me"
url = "/about/"
weight = 20

[[main]]
name = "Posts"
title = "Posts"
url = "/posts/"
weight = 30

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/haoching"
weight = 40
