[[main]]
name = "About Me"
pageRef = "about"
weight = 20

[[main]]
name = "Posts"
pageRef = "posts"
weight = 30

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/haoching"
weight = 40
